import Image from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thiem Huynh Portfolio Site</title>
        <meta name="description" content="Generated by next.js"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="bg-blue-700 min-h-screen">
          <h1>hello</h1>
        </section>
      </main>
    </div>
  );
}
